sonar.projectKey=thiagolalmeida10-rgb
sonar.organization=thiagolalmeida10-rgb

sonar.sources=backend/src
sonar.tests=backend

sonar.test.inclusions=**/*.spect.ts

sonar.exclusions=**/node_modules/**,**/dist/**,.next/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info