sonar.projectKey=
sonar.organization=

sonar.sources=backend/src, frontend
sonar.exclusions=**/node_modules/**,**/dist/**,.next/**

sonar.tests=backend
sonar.test.inclusions=**/*.spect.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info